name: Create image Redis 

on:
  workflow_dispatch: # dÃ©clenchement manuel depuis lâ€™onglet Actions

jobs:
  create-image:
    runs-on: 
        - self-hosted
        - runner-test

    steps:
      - name: VÃ©rifier le runner
        run: echo "Hello ğŸš€ je tourne bien sur mon runner self-hosted 'self-hosted-runners'" && docker compose ls
